export const BASIC_WORDS_100 = [
  { english: 'the', russian: 'этот' },
  { english: 'be', russian: 'быть' },
  { english: 'to', russian: 'к, в' },
  { english: 'of', russian: 'из, о' },
  { english: 'and', russian: 'и' },
  { english: 'a', russian: 'один, какой-то' },
  { english: 'in', russian: 'в, внутри' },
  { english: 'that', russian: 'что, тот' },
  { english: 'have', russian: 'иметь' },
  { english: 'I', russian: 'я' },
  { english: 'it', russian: 'оно, это' },
  { english: 'for', russian: 'для' },
  { english: 'not', russian: 'не' },
  { english: 'on', russian: 'на' },
  { english: 'with', russian: 'с' },
  { english: 'he', russian: 'он' },
  { english: 'as', russian: 'как' },
  { english: 'you', russian: 'ты, вы' },
  { english: 'do', russian: 'делать' },
  { english: 'at', russian: 'в, у, на' },
  { english: 'this', russian: 'этот' },
  { english: 'but', russian: 'но' },
  { english: 'his', russian: 'его' },
  { english: 'by', russian: 'у, около, к' },
  { english: 'from', russian: 'из, от' },
  { english: 'they', russian: 'они' },
  { english: 'we', russian: 'мы' },
  { english: 'say', russian: 'говорить, сказать' },
  { english: 'her', russian: 'её' },
  { english: 'she', russian: 'она' },
  { english: 'or', russian: 'или' },
  { english: 'an', russian: 'один' },
  { english: 'will', russian: 'будет' },
  { english: 'my', russian: 'мой' },
  { english: 'one', russian: 'один' },
  { english: 'all', russian: 'все' },
  { english: 'would', russian: 'бы' },
  { english: 'there', russian: 'там' },
  { english: 'their', russian: 'их' },
  { english: 'what', russian: 'что' },
  { english: 'so', russian: 'так, поэтому' },
  { english: 'up', russian: 'вверх' },
  { english: 'out', russian: 'вне, снаружи' },
  { english: 'if', russian: 'если' },
  { english: 'about', russian: 'о, около' },
  { english: 'who', russian: 'кто' },
  { english: 'get', russian: 'получать' },
  { english: 'which', russian: 'который' },
  { english: 'go', russian: 'идти' },
  { english: 'me', russian: 'меня' },
  { english: 'know', russian: 'знать' },
  { english: 'other', russian: 'другой' },
  { english: 'its', russian: 'его, её (неодуш.)' },
  { english: 'time', russian: 'время' },
  { english: 'has', russian: 'имеет' },
  { english: 'two', russian: 'два' },
  { english: 'more', russian: 'больше' },
  { english: 'write', russian: 'писать' },
  { english: 'number', russian: 'число, номер' },
  { english: 'no', russian: 'нет' },
  { english: 'way', russian: 'путь, способ' },
  { english: 'could', russian: 'мог бы' },
  { english: 'people', russian: 'люди' },
  { english: 'than', russian: 'чем' },
  { english: 'first', russian: 'первый' },
  { english: 'water', russian: 'вода' },
  { english: 'call', russian: 'звонить, называть' },
  { english: 'been', russian: 'был' },
  { english: 'oil', russian: 'масло' },
  { english: 'sit', russian: 'сидеть' },
  { english: 'now', russian: 'сейчас' },
  { english: 'find', russian: 'находить' },
  { english: 'long', russian: 'длинный, долго' },
  { english: 'down', russian: 'вниз' },
  { english: 'day', russian: 'день' },
  { english: 'did', russian: 'делал' },
  { english: 'come', russian: 'приходить' },
  { english: 'made', russian: 'сделанный' },
  { english: 'may', russian: 'может' },
  { english: 'part', russian: 'часть' }
];