export interface GrammarTopic {
  id: string
  title: string
  description: string
  level: 'beginner' | 'intermediate' | 'advanced'
  completed: boolean
  locked: boolean
  prerequisiteIds?: string[]
}

export const GRAMMAR_TOPICS: GrammarTopic[] = [
  {
    id: 'to-be',
    title: 'Глагол to be',
    description: 'Формы am, is, are, was, were — самый важный глагол английского',
    level: 'beginner',
    completed: false,
    locked: false,
  },
  {
    id: 'articles',
    title: 'Articles',
    description: 'Артикли a, an, the',
    level: 'beginner',
    completed: false,
    locked: false,
  },
  {
    id: 'present-simple',
    title: 'Present Simple',
    description: 'Основы настоящего простого времени',
    level: 'beginner',
    completed: false,
    locked: false,
  },
  {
    id: 'present-continuous',
    title: 'Present Continuous',
    description: 'Настоящее длительное время',
    level: 'beginner',
    completed: false,
    locked: false,
  },
  {
    id: 'past-simple',
    title: 'Past Simple',
    description: 'Прошедшее простое время',
    level: 'beginner',
    completed: false,
    locked: false,
  },
  {
    id: 'future-simple',
    title: 'Future Simple',
    description: 'Будущее простое время',
    level: 'beginner',
    completed: false,
    locked: false,
  },
  {
    id: 'modal-verbs',
    title: 'Modal Verbs',
    description: 'Модальные глаголы (can, must, should, etc.)',
    level: 'beginner',
    completed: false,
    locked: false,
  },
  {
    id: 'there-is-are',
    title: 'There is / There are',
    description: 'Как сказать «есть» или «находится»',
    level: 'beginner',
    completed: false,
    locked: false,
  },
  {
    id: 'prepositions',
    title: 'Prepositions',
    description: 'Предлоги места и времени',
    level: 'beginner',
    completed: false,
    locked: false,
  },
  {
    id: 'question-words',
    title: 'Question Words',
    description: 'Вопросительные слова (what, where, when, why, how)',
    level: 'beginner',
    completed: false,
    locked: false,
  },
  {
    id: 'possessive-pronouns',
    title: 'Possessive Pronouns',
    description: 'Притяжательные местоимения (my, your, his, her, its, our, their)',
    level: 'beginner',
    completed: false,
    locked: false,
  },
  {
    id: 'demonstrative-pronouns',
    title: 'Demonstrative Pronouns',
    description: 'Указательные местоимения (this, that, these, those)',
    level: 'beginner',
    completed: false,
    locked: false,
  },
  {
    id: 'countable-uncountable',
    title: 'Countable / Uncountable Nouns',
    description: 'Исчисляемые и неисчисляемые существительные',
    level: 'beginner',
    completed: false,
    locked: false,
  },
  {
    id: 'comparative-superlative',
    title: 'Comparative & Superlative',
    description: 'Сравнительная и превосходная степени прилагательных',
    level: 'beginner',
    completed: false,
    locked: false,
  },
  {
    id: 'present-perfect',
    title: 'Present Perfect',
    description: 'Настоящее совершённое время',
    level: 'intermediate',
    completed: false,
    locked: false,
  },
  {
    id: 'past-continuous',
    title: 'Past Continuous',
    description: 'Прошедшее длительное время',
    level: 'intermediate',
    completed: false,
    locked: false,
  },
  {
    id: 'present-perfect-continuous',
    title: 'Present Perfect Continuous',
    description: 'Настоящее совершённое длительное — действие, длившееся до сих пор',
    level: 'intermediate',
    completed: false,
    locked: false,
  },
  {
    id: 'past-perfect',
    title: 'Past Perfect',
    description: 'Прошедшее совершённое — действие до другого прошедшего',
    level: 'intermediate',
    completed: false,
    locked: false,
  },
  {
    id: 'future-forms',
    title: 'Future Forms (be going to, Present Continuous)',
    description: 'Все способы выразить будущее: will, be going to, Present Continuous',
    level: 'intermediate',
    completed: false,
    locked: false,
  },
  {
    id: 'passive-voice',
    title: 'Passive Voice',
    description: 'Страдательный залог: when the object becomes the subject',
    level: 'intermediate',
    completed: false,
    locked: false,
  },
  {
    id: 'conditionals',
    title: 'Conditionals (0, 1, 2, 3)',
    description: 'Условные предложения: реальные, нереальные, прошедшие',
    level: 'intermediate',
    completed: false,
    locked: false,
  },
  {
    id: 'reported-speech',
    title: 'Reported Speech',
    description: 'Косвенная речь: передаём чужие слова',
    level: 'intermediate',
    completed: false,
    locked: false,
  },
  {
    id: 'gerund-infinitive',
    title: 'Gerund vs Infinitive',
    description: 'Герундий и инфинитив: когда какой использовать',
    level: 'intermediate',
    completed: false,
    locked: false,
  },
  {
    id: 'phrasal-verbs',
    title: 'Phrasal Verbs',
    description: 'Фразовые глаголы: look up, give up, turn on и др.',
    level: 'intermediate',
    completed: false,
    locked: false,
  },
  {
    id: 'relative-clauses',
    title: 'Relative Clauses',
    description: 'Придаточные определительные: who, which, that, whose',
    level: 'intermediate',
    completed: false,
    locked: false,
  },
  {
    id: 'used-to-would',
    title: 'Used to / Would / Be used to',
    description: 'Привычки в прошлом и привычки сейчас',
    level: 'intermediate',
    completed: false,
    locked: false,
  },
  {
    id: 'linking-words',
    title: 'Linking Words',
    description: 'Связующие слова: however, therefore, moreover, although',
    level: 'advanced',
    completed: false,
    locked: false,
  },
  {
    id: 'inversion',
    title: 'Inversion',
    description: 'Инверсия: Never have I, Had I known, Not only...',
    level: 'advanced',
    completed: false,
    locked: false,
  },
  {
    id: 'subjunctive',
    title: 'Subjunctive Mood',
    description: 'Сослагательное наклонение: I wish, If only, It\'s time',
    level: 'advanced',
    completed: false,
    locked: false,
  },
  {
    id: 'complex-gerund',
    title: 'Complex Gerund & Perfect Infinitive',
    description: 'Сложные формы: having done, to have done',
    level: 'advanced',
    completed: false,
    locked: false,
  },
]