export interface WordCategory {
  id: string
  name: string
  icon: string
  words: { english: string; russian: string }[]
}

export const WORD_CATEGORIES: WordCategory[] = [
  {
    id: 'travel',
    name: 'Путешествия',
    icon: '✈️',
    words: [
      { english: 'airport', russian: 'аэропорт' },
      { english: 'flight', russian: 'рейс' },
      { english: 'ticket', russian: 'билет' },
      { english: 'passport', russian: 'паспорт' },
      { english: 'luggage', russian: 'багаж' },
      { english: 'hotel', russian: 'отель' },
      { english: 'reservation', russian: 'бронирование' },
      { english: 'boarding pass', russian: 'посадочный талон' },
      { english: 'customs', russian: 'таможня' },
      { english: 'delay', russian: 'задержка' },
      { english: 'gate', russian: 'выход (на посадку)' },
      { english: 'terminal', russian: 'терминал' },
      { english: 'aisle seat', russian: 'место у прохода' },
      { english: 'window seat', russian: 'место у окна' },
      { english: 'check-in', russian: 'регистрация' },
      { english: 'destination', russian: 'пункт назначения' },
      { english: 'departure', russian: 'отправление' },
      { english: 'arrival', russian: 'прибытие' },
      { english: 'suitcase', russian: 'чемодан' },
      { english: 'backpack', russian: 'рюкзак' },
      { english: 'tourist', russian: 'турист' },
      { english: 'guide', russian: 'гид' },
      { english: 'map', russian: 'карта' },
      { english: 'souvenir', russian: 'сувенир' },
      { english: 'currency', russian: 'валюта' },
      { english: 'exchange rate', russian: 'курс обмена' },
      { english: 'visa', russian: 'виза' },
      { english: 'insurance', russian: 'страховка' },
      { english: 'sightseeing', russian: 'осмотр достопримечательностей' },
      { english: 'landmark', russian: 'достопримечательность' },
    ],
  },
  {
    id: 'work',
    name: 'Работа',
    icon: '💼',
    words: [
      { english: 'employee', russian: 'сотрудник' },
      { english: 'employer', russian: 'работодатель' },
      { english: 'colleague', russian: 'коллега' },
      { english: 'manager', russian: 'менеджер' },
      { english: 'boss', russian: 'начальник' },
      { english: 'interview', russian: 'собеседование' },
      { english: 'resume', russian: 'резюме' },
      { english: 'salary', russian: 'зарплата' },
      { english: 'wage', russian: 'ставка' },
      { english: 'promotion', russian: 'повышение' },
      { english: 'deadline', russian: 'дедлайн' },
      { english: 'meeting', russian: 'совещание' },
      { english: 'presentation', russian: 'презентация' },
      { english: 'report', russian: 'отчёт' },
      { english: 'project', russian: 'проект' },
      { english: 'task', russian: 'задача' },
      { english: 'schedule', russian: 'расписание' },
      { english: 'overtime', russian: 'сверхурочные' },
      { english: 'experience', russian: 'опыт' },
      { english: 'skill', russian: 'навык' },
      { english: 'contract', russian: 'контракт' },
      { english: 'client', russian: 'клиент' },
      { english: 'feedback', russian: 'обратная связь' },
      { english: 'resign', russian: 'уволиться' },
      { english: 'hire', russian: 'нанимать' },
      { english: 'fire', russian: 'уволить' },
      { english: 'remote work', russian: 'удалённая работа' },
      { english: 'office', russian: 'офис' },
      { english: 'department', russian: 'отдел' },
      { english: 'colleague', russian: 'коллега' },
    ],
  },
  {
    id: 'verbs',
    name: 'Базовые глаголы',
    icon: '⚡',
    words: [
      { english: 'be', russian: 'быть' },
      { english: 'have', russian: 'иметь' },
      { english: 'do', russian: 'делать' },
      { english: 'go', russian: 'идти' },
      { english: 'come', russian: 'приходить' },
      { english: 'get', russian: 'получать' },
      { english: 'make', russian: 'делать, создавать' },
      { english: 'take', russian: 'брать' },
      { english: 'see', russian: 'видеть' },
      { english: 'know', russian: 'знать' },
      { english: 'think', russian: 'думать' },
      { english: 'say', russian: 'говорить' },
      { english: 'tell', russian: 'рассказывать' },
      { english: 'ask', russian: 'спрашивать' },
      { english: 'give', russian: 'давать' },
      { english: 'find', russian: 'находить' },
      { english: 'feel', russian: 'чувствовать' },
      { english: 'become', russian: 'становиться' },
      { english: 'leave', russian: 'уходить, оставлять' },
      { english: 'put', russian: 'класть' },
      { english: 'mean', russian: 'значить' },
      { english: 'keep', russian: 'держать, сохранять' },
      { english: 'let', russian: 'позволять' },
      { english: 'begin', russian: 'начинать' },
      { english: 'seem', russian: 'казаться' },
      { english: 'help', russian: 'помогать' },
      { english: 'show', russian: 'показывать' },
      { english: 'hear', russian: 'слышать' },
      { english: 'play', russian: 'играть' },
      { english: 'run', russian: 'бежать' },
    ],
  },
  {
    id: 'nouns',
    name: 'Базовые существительные',
    icon: '📦',
    words: [
      { english: 'time', russian: 'время' },
      { english: 'person', russian: 'человек' },
      { english: 'year', russian: 'год' },
      { english: 'way', russian: 'путь, способ' },
      { english: 'day', russian: 'день' },
      { english: 'thing', russian: 'вещь' },
      { english: 'man', russian: 'мужчина' },
      { english: 'woman', russian: 'женщина' },
      { english: 'life', russian: 'жизнь' },
      { english: 'child', russian: 'ребёнок' },
      { english: 'world', russian: 'мир' },
      { english: 'school', russian: 'школа' },
      { english: 'family', russian: 'семья' },
      { english: 'group', russian: 'группа' },
      { english: 'country', russian: 'страна' },
      { english: 'problem', russian: 'проблема' },
      { english: 'hand', russian: 'рука' },
      { english: 'part', russian: 'часть' },
      { english: 'place', russian: 'место' },
      { english: 'case', russian: 'случай' },
      { english: 'week', russian: 'неделя' },
      { english: 'company', russian: 'компания' },
      { english: 'system', russian: 'система' },
      { english: 'program', russian: 'программа' },
      { english: 'question', russian: 'вопрос' },
      { english: 'government', russian: 'правительство' },
      { english: 'number', russian: 'число' },
      { english: 'night', russian: 'ночь' },
      { english: 'point', russian: 'точка, момент' },
      { english: 'home', russian: 'дом' },
    ],
  },
  {
    id: 'food',
    name: 'Еда и ресторан',
    icon: '🍽️',
    words: [
      { english: 'breakfast', russian: 'завтрак' },
      { english: 'lunch', russian: 'обед' },
      { english: 'dinner', russian: 'ужин' },
      { english: 'menu', russian: 'меню' },
      { english: 'bill', russian: 'счёт' },
      { english: 'tip', russian: 'чаевые' },
      { english: 'waiter', russian: 'официант' },
      { english: 'reservation', russian: 'бронь' },
      { english: 'spicy', russian: 'острый' },
      { english: 'delicious', russian: 'вкусный' },
      { english: 'vegetarian', russian: 'вегетарианский' },
      { english: 'allergic', russian: 'аллергия' },
      { english: 'ingredients', russian: 'ингредиенты' },
      { english: 'rare', russian: 'с кровью (стейк)' },
      { english: 'medium', russian: 'средней прожарки' },
      { english: 'well done', russian: 'хорошо прожаренный' },
      { english: 'appetizer', russian: 'закуска' },
      { english: 'dessert', russian: 'десерт' },
      { english: 'beverage', russian: 'напиток' },
      { english: 'napkin', russian: 'салфетка' },
    ],
  },
  {
    id: 'emotions',
    name: 'Эмоции и чувства',
    icon: '❤️',
    words: [
      { english: 'happy', russian: 'счастливый' },
      { english: 'sad', russian: 'грустный' },
      { english: 'angry', russian: 'злой' },
      { english: 'tired', russian: 'уставший' },
      { english: 'excited', russian: 'взволнованный' },
      { english: 'nervous', russian: 'нервный' },
      { english: 'surprised', russian: 'удивлённый' },
      { english: 'bored', russian: 'скучающий' },
      { english: 'confused', russian: 'смущённый' },
      { english: 'worried', russian: 'обеспокоенный' },
      { english: 'proud', russian: 'гордый' },
      { english: 'embarrassed', russian: 'смущённый' },
      { english: 'jealous', russian: 'ревнивый' },
      { english: 'grateful', russian: 'благодарный' },
      { english: 'disappointed', russian: 'разочарованный' },
      { english: 'relieved', russian: 'облегчённый' },
      { english: 'anxious', russian: 'тревожный' },
      { english: 'curious', russian: 'любопытный' },
      { english: 'lonely', russian: 'одинокий' },
      { english: 'hopeful', russian: 'надеющийся' },
    ],
  },
  {
    id: 'it',
    name: 'IT и технологии',
    icon: '💻',
    words: [
      { english: 'software', russian: 'программное обеспечение' },
      { english: 'hardware', russian: 'аппаратное обеспечение' },
      { english: 'developer', russian: 'разработчик' },
      { english: 'debug', russian: 'отлаживать' },
      { english: 'bug', russian: 'ошибка, баг' },
      { english: 'feature', russian: 'функция, особенность' },
      { english: 'deploy', russian: 'развёртывать' },
      { english: 'repository', russian: 'хранилище, репозиторий' },
      { english: 'commit', russian: 'коммит, фиксировать изменения' },
      { english: 'branch', russian: 'ветка' },
      { english: 'merge', russian: 'объединять' },
      { english: 'pull request', russian: 'запрос на внесение изменений' },
      { english: 'framework', russian: 'фреймворк' },
      { english: 'library', russian: 'библиотека' },
      { english: 'API', russian: 'интерфейс прикладного программирования' },
      { english: 'database', russian: 'база данных' },
      { english: 'server', russian: 'сервер' },
      { english: 'client', russian: 'клиент' },
      { english: 'request', russian: 'запрос' },
      { english: 'response', russian: 'ответ' },
      { english: 'endpoint', russian: 'конечная точка' },
      { english: 'authentication', russian: 'аутентификация' },
      { english: 'authorization', russian: 'авторизация' },
      { english: 'encryption', russian: 'шифрование' },
      { english: 'algorithm', russian: 'алгоритм' },
      { english: 'variable', russian: 'переменная' },
      { english: 'function', russian: 'функция' },
      { english: 'loop', russian: 'цикл' },
      { english: 'condition', russian: 'условие' },
      { english: 'array', russian: 'массив' },
      { english: 'object', russian: 'объект' },
      { english: 'class', russian: 'класс' },
      { english: 'interface', russian: 'интерфейс' },
      { english: 'inheritance', russian: 'наследование' },
      { english: 'polymorphism', russian: 'полиморфизм' },
      { english: 'encapsulation', russian: 'инкапсуляция' },
      { english: 'refactor', russian: 'рефакторинг' },
      { english: 'test', russian: 'тест' },
      { english: 'unit test', russian: 'модульное тестирование' },
      { english: 'integration test', russian: 'интеграционное тестирование' },
    ],
  },
  {
    id: 'parts-of-speech',
    name: 'Части речи',
    icon: '📚',
    words: [
      { english: 'noun', russian: 'существительное' },
      { english: 'verb', russian: 'глагол' },
      { english: 'adjective', russian: 'прилагательное' },
      { english: 'adverb', russian: 'наречие' },
      { english: 'pronoun', russian: 'местоимение' },
      { english: 'preposition', russian: 'предлог' },
      { english: 'conjunction', russian: 'союз' },
      { english: 'interjection', russian: 'междометие' },
      { english: 'article', russian: 'артикль' },
      { english: 'subject', russian: 'подлежащее' },
      { english: 'predicate', russian: 'сказуемое' },
      { english: 'object', russian: 'дополнение' },
      { english: 'clause', russian: 'придаточное предложение' },
      { english: 'phrase', russian: 'фраза, словосочетание' },
      { english: 'sentence', russian: 'предложение' },
      { english: 'tense', russian: 'время' },
      { english: 'aspect', russian: 'вид' },
      { english: 'mood', russian: 'наклонение' },
      { english: 'voice', russian: 'залог' },
      { english: 'gender', russian: 'род' },
      { english: 'number', russian: 'число' },
      { english: 'case', russian: 'падеж' },
    ],
  },
  {
    id: 'phrasal-verbs',
    name: 'Фразовые глаголы',
    icon: '🔗',
    words: [
      { english: 'give up', russian: 'бросать, сдаваться' },
      { english: 'look after', russian: 'заботиться' },
      { english: 'look forward to', russian: 'с нетерпением ждать' },
      { english: 'find out', russian: 'узнавать' },
      { english: 'get along', russian: 'ладить' },
      { english: 'get over', russian: 'преодолеть' },
      { english: 'bring up', russian: 'воспитывать, поднимать тему' },
      { english: 'call off', russian: 'отменять' },
      { english: 'carry on', russian: 'продолжать' },
      { english: 'come across', russian: 'наталкиваться' },
      { english: 'cut off', russian: 'отрезать, отключать' },
      { english: 'drop by', russian: 'заходить в гости' },
      { english: 'figure out', russian: 'разобраться' },
      { english: 'get away', russian: 'убежать, уехать' },
      { english: 'go through', russian: 'проходить через' },
      { english: 'hold on', russian: 'подождать' },
      { english: 'keep up', russian: 'поддерживать' },
      { english: 'let down', russian: 'подводить' },
      { english: 'look into', russian: 'расследовать' },
      { english: 'make up', russian: 'выдумывать, мириться' },
      { english: 'pass out', russian: 'потерять сознание' },
      { english: 'pick up', russian: 'подбирать, поднимать' },
      { english: 'put off', russian: 'откладывать' },
      { english: 'put up with', russian: 'терпеть' },
      { english: 'run into', russian: 'встретить случайно' },
      { english: 'set up', russian: 'настраивать, создавать' },
      { english: 'take after', russian: 'походить на' },
      { english: 'take off', russian: 'снимать, взлетать' },
      { english: 'turn down', russian: 'отклонять, убавлять' },
      { english: 'turn up', russian: 'появляться, увеличивать' },
    ],
  },
  {
    id: 'business',
    name: 'Бизнес',
    icon: '📈',
    words: [
      { english: 'investment', russian: 'инвестиция' },
      { english: 'profit', russian: 'прибыль' },
      { english: 'loss', russian: 'убыток' },
      { english: 'revenue', russian: 'выручка' },
      { english: 'budget', russian: 'бюджет' },
      { english: 'marketing', russian: 'маркетинг' },
      { english: 'sales', russian: 'продажи' },
      { english: 'customer', russian: 'клиент' },
      { english: 'competition', russian: 'конкуренция' },
      { english: 'strategy', russian: 'стратегия' },
      { english: 'target audience', russian: 'целевая аудитория' },
      { english: 'brand', russian: 'бренд' },
      { english: 'startup', russian: 'стартап' },
      { english: 'partnership', russian: 'партнёрство' },
      { english: 'merger', russian: 'слияние' },
      { english: 'acquisition', russian: 'поглощение' },
      { english: 'quarterly report', russian: 'квартальный отчёт' },
      { english: 'cash flow', russian: 'денежный поток' },
      { english: 'assets', russian: 'активы' },
      { english: 'liabilities', russian: 'обязательства' },
      { english: 'equity', russian: 'собственный капитал' },
      { english: 'dividend', russian: 'дивиденд' },
      { english: 'stock', russian: 'акция' },
      { english: 'shareholder', russian: 'акционер' },
      { english: 'CEO', russian: 'генеральный директор' },
      { english: 'CFO', russian: 'финансовый директор' },
      { english: 'COO', russian: 'операционный директор' },
      { english: 'board of directors', russian: 'совет директоров' },
      { english: 'meeting', russian: 'встреча, совещание' },
      { english: 'negotiation', russian: 'переговоры' },
    ],
  },
  {
    id: 'daily-life',
    name: 'Повседневная жизнь',
    icon: '🏠',
    words: [
      { english: 'morning', russian: 'утро' },
      { english: 'evening', russian: 'вечер' },
      { english: 'night', russian: 'ночь' },
      { english: 'weekend', russian: 'выходные' },
      { english: 'holiday', russian: 'праздник, отпуск' },
      { english: 'chores', russian: 'домашние дела' },
      { english: 'grocery', russian: 'продукты' },
      { english: 'laundry', russian: 'стирка' },
      { english: 'cooking', russian: 'готовка' },
      { english: 'cleaning', russian: 'уборка' },
      { english: 'garden', russian: 'сад' },
      { english: 'repair', russian: 'ремонт' },
      { english: 'furniture', russian: 'мебель' },
      { english: 'appliance', russian: 'бытовая техника' },
      { english: 'utility bill', russian: 'коммунальные платежи' },
      { english: 'rent', russian: 'аренда' },
      { english: 'neighbor', russian: 'сосед' },
      { english: 'community', russian: 'сообщество' },
      { english: 'exercise', russian: 'упражнения' },
      { english: 'hobby', russian: 'хобби' },
      { english: 'relax', russian: 'расслабляться' },
      { english: 'sleep', russian: 'сон' },
      { english: 'dream', russian: 'мечта, сон' },
      { english: 'wake up', russian: 'просыпаться' },
      { english: 'shower', russian: 'душ' },
      { english: 'breakfast', russian: 'завтрак' },
      { english: 'commute', russian: 'дорога на работу' },
      { english: 'rush hour', russian: 'час пик' },
      { english: 'traffic', russian: 'пробка' },
      { english: 'parking', russian: 'парковка' },
    ],
  },
]
