export interface WordCategory {
  id: string
  name: string
  icon: string
  words: { english: string; russian: string }[]
}

export const WORD_CATEGORIES: WordCategory[] = [
  {
    id: 'travel',
    name: 'Путешествия',
    icon: '✈️',
    words: [
      { english: 'airport', russian: 'аэропорт' },
      { english: 'flight', russian: 'рейс' },
      { english: 'ticket', russian: 'билет' },
      { english: 'passport', russian: 'паспорт' },
      { english: 'luggage', russian: 'багаж' },
      { english: 'hotel', russian: 'отель' },
      { english: 'reservation', russian: 'бронирование' },
      { english: 'boarding pass', russian: 'посадочный талон' },
      { english: 'customs', russian: 'таможня' },
      { english: 'delay', russian: 'задержка' },
      { english: 'gate', russian: 'выход (на посадку)' },
      { english: 'terminal', russian: 'терминал' },
      { english: 'aisle seat', russian: 'место у прохода' },
      { english: 'window seat', russian: 'место у окна' },
      { english: 'check-in', russian: 'регистрация' },
      { english: 'destination', russian: 'пункт назначения' },
      { english: 'departure', russian: 'отправление' },
      { english: 'arrival', russian: 'прибытие' },
      { english: 'suitcase', russian: 'чемодан' },
      { english: 'backpack', russian: 'рюкзак' },
      { english: 'tourist', russian: 'турист' },
      { english: 'guide', russian: 'гид' },
      { english: 'map', russian: 'карта' },
      { english: 'souvenir', russian: 'сувенир' },
      { english: 'currency', russian: 'валюта' },
      { english: 'exchange rate', russian: 'курс обмена' },
      { english: 'visa', russian: 'виза' },
      { english: 'insurance', russian: 'страховка' },
      { english: ' sightseeing', russian: 'осмотр достопримечательностей' },
      { english: 'landmark', russian: 'достопримечательность' },
    ],
  },
  {
    id: 'work',
    name: 'Работа',
    icon: '💼',
    words: [
      { english: 'employee', russian: 'сотрудник' },
      { english: 'employer', russian: 'работодатель' },
      { english: 'colleague', russian: 'коллега' },
      { english: 'manager', russian: 'менеджер' },
      { english: 'boss', russian: 'начальник' },
      { english: 'interview', russian: 'собеседование' },
      { english: 'resume', russian: 'резюме' },
      { english: 'salary', russian: 'зарплата' },
      { english: 'wage', russian: 'ставка' },
      { english: 'promotion', russian: 'повышение' },
      { english: 'deadline', russian: 'дедлайн' },
      { english: 'meeting', russian: 'совещание' },
      { english: 'presentation', russian: 'презентация' },
      { english: 'report', russian: 'отчёт' },
      { english: 'project', russian: 'проект' },
      { english: 'task', russian: 'задача' },
      { english: 'schedule', russian: 'расписание' },
      { english: 'overtime', russian: 'сверхурочные' },
      { english: 'experience', russian: 'опыт' },
      { english: 'skill', russian: 'навык' },
      { english: 'contract', russian: 'контракт' },
      { english: 'client', russian: 'клиент' },
      { english: 'deadline', russian: 'крайний срок' },
      { english: 'feedback', russian: 'обратная связь' },
      { english: 'resign', russian: 'уволиться' },
      { english: 'hire', russian: 'нанимать' },
      { english: 'fire', russian: 'уволить' },
      { english: 'remote work', russian: 'удалённая работа' },
      { english: 'office', russian: 'офис' },
      { english: 'department', russian: 'отдел' },
    ],
  },
  {
    id: 'verbs',
    name: 'Базовые глаголы',
    icon: '⚡',
    words: [
      { english: 'be', russian: 'быть' },
      { english: 'have', russian: 'иметь' },
      { english: 'do', russian: 'делать' },
      { english: 'go', russian: 'идти' },
      { english: 'come', russian: 'приходить' },
      { english: 'get', russian: 'получать' },
      { english: 'make', russian: 'делать, создавать' },
      { english: 'take', russian: 'брать' },
      { english: 'see', russian: 'видеть' },
      { english: 'know', russian: 'знать' },
      { english: 'think', russian: 'думать' },
      { english: 'say', russian: 'говорить' },
      { english: 'tell', russian: 'рассказывать' },
      { english: 'ask', russian: 'спрашивать' },
      { english: 'give', russian: 'давать' },
      { english: 'find', russian: 'находить' },
      { english: 'feel', russian: 'чувствовать' },
      { english: 'become', russian: 'становиться' },
      { english: 'leave', russian: 'уходить, оставлять' },
      { english: 'put', russian: 'класть' },
      { english: 'mean', russian: 'значить' },
      { english: 'keep', russian: 'держать, сохранять' },
      { english: 'let', russian: 'позволять' },
      { english: 'begin', russian: 'начинать' },
      { english: 'seem', russian: 'казаться' },
      { english: 'help', russian: 'помогать' },
      { english: 'show', russian: 'показывать' },
      { english: 'hear', russian: 'слышать' },
      { english: 'play', russian: 'играть' },
      { english: 'run', russian: 'бежать' },
    ],
  },
  {
    id: 'nouns',
    name: 'Базовые существительные',
    icon: '📦',
    words: [
      { english: 'time', russian: 'время' },
      { english: 'person', russian: 'человек' },
      { english: 'year', russian: 'год' },
      { english: 'way', russian: 'путь, способ' },
      { english: 'day', russian: 'день' },
      { english: 'thing', russian: 'вещь' },
      { english: 'man', russian: 'мужчина' },
      { english: 'woman', russian: 'женщина' },
      { english: 'life', russian: 'жизнь' },
      { english: 'child', russian: 'ребёнок' },
      { english: 'world', russian: 'мир' },
      { english: 'school', russian: 'школа' },
      { english: 'family', russian: 'семья' },
      { english: 'group', russian: 'группа' },
      { english: 'country', russian: 'страна' },
      { english: 'problem', russian: 'проблема' },
      { english: 'hand', russian: 'рука' },
      { english: 'part', russian: 'часть' },
      { english: 'place', russian: 'место' },
      { english: 'case', russian: 'случай' },
      { english: 'week', russian: 'неделя' },
      { english: 'company', russian: 'компания' },
      { english: 'system', russian: 'система' },
      { english: 'program', russian: 'программа' },
      { english: 'question', russian: 'вопрос' },
      { english: 'government', russian: 'правительство' },
      { english: 'number', russian: 'число' },
      { english: 'night', russian: 'ночь' },
      { english: 'point', russian: 'точка, момент' },
      { english: 'home', russian: 'дом' },
    ],
  },
  {
    id: 'food',
    name: 'Еда и ресторан',
    icon: '🍽️',
    words: [
      { english: 'breakfast', russian: 'завтрак' },
      { english: 'lunch', russian: 'обед' },
      { english: 'dinner', russian: 'ужин' },
      { english: 'menu', russian: 'меню' },
      { english: 'bill', russian: 'счёт' },
      { english: 'tip', russian: 'чаевые' },
      { english: 'waiter', russian: 'официант' },
      { english: 'reservation', russian: 'бронь' },
      { english: 'spicy', russian: 'острый' },
      { english: 'delicious', russian: 'вкусный' },
      { english: 'vegetarian', russian: 'вегетарианский' },
      { english: 'allergic', russian: 'аллергия' },
      { english: 'ingredients', russian: 'ингредиенты' },
      { english: 'rare', russian: 'с кровью (стейк)' },
      { english: 'medium', russian: 'средней прожарки' },
      { english: 'well done', russian: 'хорошо прожаренный' },
      { english: 'appetizer', russian: 'закуска' },
      { english: 'dessert', russian: 'десерт' },
      { english: 'beverage', russian: 'напиток' },
      { english: 'napkin', russian: 'салфетка' },
    ],
  },
  {
    id: 'emotions',
    name: 'Эмоции и чувства',
    icon: '❤️',
    words: [
      { english: 'happy', russian: 'счастливый' },
      { english: 'sad', russian: 'грустный' },
      { english: 'angry', russian: 'злой' },
      { english: 'tired', russian: 'уставший' },
      { english: 'excited', russian: 'взволнованный' },
      { english: 'nervous', russian: 'нервный' },
      { english: 'surprised', russian: 'удивлённый' },
      { english: 'bored', russian: 'скучающий' },
      { english: 'confused', russian: 'смущённый' },
      { english: 'worried', russian: 'обеспокоенный' },
      { english: 'proud', russian: 'гордый' },
      { english: 'embarrassed', russian: 'смущённый' },
      { english: 'jealous', russian: 'ревнивый' },
      { english: 'grateful', russian: 'благодарный' },
      { english: 'disappointed', russian: 'разочарованный' },
      { english: 'relieved', russian: 'облегчённый' },
      { english: 'anxious', russian: 'тревожный' },
      { english: 'curious', russian: 'любопытный' },
      { english: 'lonely', russian: 'одинокий' },
      { english: 'hopeful', russian: 'надеющийся' },
    ],
  },
]
